name: 3Laws7Rules
favicon: null
layout_spectrum: 0.9554680984001607
typography_spectrum: 0.32339517609216273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6591359591111541
  lightness: 0.4441353993024677
  saturation: 0.6308296769857407
  rhythmicContrast: 0.2595386258326471
purpose: []
