name: 3Laws7Rules
favicon: null
layout_spectrum: 0.17611
typography_spectrum: 0.75267
title: The Three Laws and Seven Rules to Create a Harmonious Planet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070206'
    - '#ffffff'
    - '#655f81'
    - '#998baf'
    - '#e1c0c7'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
