name: 3Laws7Rules
favicon: null
layout_spectrum: 0.17611
typography_spectrum: 0.75267
title: The Three Laws and Seven Rules to Create a Harmonious Planet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d3d5f'
    - '#d6b2a2'
    - '#8a5c45'
    - '#45ae49'
    - '#ccf0cb'
  brandStrength: 0.25
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
